### ISSUE TITLE
Detect and adapt to different supported fan speeds

### ISSUE THREAD

**Issue by gogreenpower** [nathanvdh/homeassistant-airtouch2#2] opened 2022-09-25 14:25 UTC
Hi mate, great work. Just been playing around and noticed the fan level set in the integration is one level higher than the unit. Low is medium, medium is high, high is diffuse (which I don't have on my unit) and diffuse is low. Auto is good.

**Comment by nathanvdh** [comment] 2022-09-25 22:36
What brand is your ac unit?

**Comment by gogreenpower** [comment] 2022-09-26 00:47
Fujitsu

**Comment by nathanvdh** [comment] 2022-09-26 01:32
Hm so is mine - will have to investigate, likely with some help from you.

**Comment by gogreenpower** [comment] 2022-09-26 01:36
No worries, just let me know what your need

**Comment by gogreenpower** [comment] 2022-09-26 13:39
I forked the repo and have found a working combination.



    ACFanSpeed.AUTO: FAN_AUTO,

    ACFanSpeed.QUIET: FAN_LOW,

    ACFanSpeed.LOW: FAN_MEDIUM,

    ACFanSpeed.HIGH: FAN_HIGH,


This updates my AT2 unit correctly. 

The original setup was doing this:

- The ACFanSpeed.MEDIUM/FAN_MEDIUM combo was setting the unit to High. 
- The ACFanSpeed.LOW/FAN_LOW combo was setting the unit to Medium.
- The ACFanSpeed.QUIET/FAN_DIFFUSE combo was setting the unit to Low.  

AUTO and HIGH combos worked correctly. Not sure if its my Fujitsu unit, I'll try and find the docs and check model numbers and if I can't, I'll climb into the roof

edit: code tags

**Comment by nathanvdh** [comment] 2022-09-27 08:21
The problem seems to be that you don't have a 'quiet' fan speed.
The values sent to the airtouch for fan speed are:
```
AUTO = 0
QUIET = 1
LOW = 2
MEDIUM = 3
HIGH = 4
```
And it seems that with 'quiet' missing, your values are offset by 1 i.e.
```
AUTO = 0
LOW = 1
MEDIUM = 2
HIGH = 3
```
so you can see where the problem is.

I'll have to see if there's a way to determine what modes a particular airtouch system supports. It must be there if everything displays and works correctly in the airtouch2 app but it hasn't been documented for airtouch2 or 3. It has for airtouch4, see here: https://github.com/LonePurpleWolf/airtouch4pyapi/blob/main/airtouch4pyapi/packetmap.py

But yeah I'm probably going to need to get a dump of the response message your airtouch unit is sending to work it out. If you have an android phone can you please force close the airtouch2 app then install 'PCAPdroid' and set it to dump to a PCAP file, set the target app to the airtouch2 app. Then just open up the app. Upload the file for me. Alternatively I can probably update my airtouch2 python client to save the response somewhere for you.

**Comment by nathanvdh** [comment] 2022-09-27 09:52
Before doing that can you confirm that the quiet speed is missing/greyed out in the app for you?
![Screenshot_20220927-192129](https://user-images.githubusercontent.com/55475809/192495294-2f91249d-3f88-4029-9548-a03d7c7b697f.png)

**Comment by gogreenpower** [comment] 2022-09-27 09:56
I'm happy to roll with what you have done. No need to do all this for just me. I'll grab those dumps anyway just in case others find the same issue.

![Screenshot_20220927-175526_AirTouch2](https://user-images.githubusercontent.com/9656919/192495868-50942ca2-5286-4e78-b20a-c15d8b070b24.jpg)

**Comment by nathanvdh** [comment] 2022-09-27 09:59
> I'm happy to roll with what you have done. No need to do all this for just me. I'll grab those dumps anyway just in case others find the same issue.
> 
> ![Screenshot_20220927-175526_AirTouch2](https://user-images.githubusercontent.com/9656919/192495868-50942ca2-5286-4e78-b20a-c15d8b070b24.jpg)

Yes please do it anyway. There is likely a bunch of information about things that supported or not so it will help solve similar issues in future

**Comment by gogreenpower** [comment] 2022-09-27 10:37
Here is the capture. I cycled though the fan speeds

[PCAP](https://drive.google.com/file/d/1KVFOhxK-ETgGhgWGxMuALzP9AiZhnxwj/view?usp=drivesdk)

**Comment by nathanvdh** [comment] 2022-09-27 11:38
The file is not public, I cannot access it.

**Comment by gogreenpower** [comment] 2022-09-27 11:46
> The file is not public, I cannot access it.

Try now

**Comment by nathanvdh** [comment] 2022-09-27 12:22
All good thanks

**Comment by ruaan-deysel** [comment] 2022-09-28 09:04
I'm experiencing the same issue on AirTouch2 controller connected to Mitsubishi Electric Ducted Aircon unit

**Comment by nathanvdh** [comment] 2022-09-28 09:47
> I'm experiencing the same issue on AirTouch2 controller connected to Mitsubishi Electric Ducted Aircon unit

Would you be able to produce the same dump for me, as I described above? The more I have from different people/units, the easier it is to reverse engineer.

**Comment by ruaan-deysel** [comment] 2022-09-28 10:31
Sure, Im iPhone user. How can I create a dump for you?

**Comment by TETZUO** [comment] 2022-09-28 10:59
Same issue with my Dakin unit. I only have low medium and high speeds

**Comment by nathanvdh** [comment] 2022-09-28 12:40
> Sure, Im iPhone user. How can I create a dump for you?

I've now added a way to dump the response from my python client. So you'll need to:
1. Go to a computer
2. Install python3
3. Run `pip3 install airtouch2` in a terminal/command window
4. Download [test.py from here](https://github.com/nathanvdh/airtouch2-python/blob/master/tests/test.py) (right click 'Raw' -> save link as test.py)
5. Open a terminal/command window and run `python3 test.py` (probably `py test.py` on windows)
6. Just type `q` and press return to quit the test program. It should have created 2 files: airtouch2.log and last_response.dump.
7. Check the airtouch2.log contains something like:
```
2022-09-28 21:38:47,892 Thread-1 (_handle_incoming) DEBUG: Received new valid response
2022-09-28 21:38:47,893 Thread-2 (_main_loop) DEBUG: 
        System Name:	NATHANVDH
        AC Name:	Fujitsu
        On:		True
        Status:		8
        Mode:		HEAT
        Fan Speed:	AUTO
        Ambient Temp:	19
        Set Temp:	19
        Manufacturer:	FUJITSU
```
8. Tell me what it says your 'manufacturer' is and what your manufacturer _really_ is (I know these are totally wrong at the moment apart from a couple)
9. Send me both airtouch2.log and last_response.dump (you can email them to me at nathanmvdh@gmail.com if you don't want to post it publicly here - it will contain all your zone names and system name and stuff).

**Comment by nathanvdh** [comment] 2022-09-28 12:41
> Same issue with my Dakin unit. I only have low medium and high speeds

Could you also produce a log and dump as I described above, the more data I have the easier it will be to support more systems.

**Comment by TETZUO** [comment] 2022-09-28 13:22
> > Same issue with my Dakin unit. I only have low medium and high speeds
> 
> Could you also produce a log and dump as I described above, the more data I have the easier it will be to support more systems.

Just sent mate. 

Manufacture is detected as “none” sent you the logs with a photo of the AirTouch unit showing Daikin

**Comment by ruaan-deysel** [comment] 2022-09-29 07:23
> > Sure, Im iPhone user. How can I create a dump for you?
> 
> I've now added a way to dump the response from my python client. So you'll need to:
> 
> 1. Go to a computer
> 2. Install python3
> 3. Run `pip3 install airtouch2` in a terminal/command window
> 4. Download [test.py from here](https://github.com/nathanvdh/airtouch2-python/blob/master/tests/test.py) (right click 'Raw' -> save link as test.py)
> 5. Open a terminal/command window and run `python3 test.py` (probably `py test.py` on windows)
> 6. Just type `q` and press return to quit the test program. It should have created 2 files: airtouch2.log and last_response.dump.
> 7. Check the airtouch2.log contains something like:
> 
> ```
> 2022-09-28 21:38:47,892 Thread-1 (_handle_incoming) DEBUG: Received new valid response
> 2022-09-28 21:38:47,893 Thread-2 (_main_loop) DEBUG: 
>         System Name:	NATHANVDH
>         AC Name:	Fujitsu
>         On:		True
>         Status:		8
>         Mode:		HEAT
>         Fan Speed:	AUTO
>         Ambient Temp:	19
>         Set Temp:	19
>         Manufacturer:	FUJITSU
> ```
> 
>  8. Tell me what it says your 'manufacturer' is and what your manufacturer _really_ is (I know these are totally wrong at the moment apart from a couple)
> 9. Send me both airtouch2.log and last_response.dump (you can email them to me at [nathanmvdh@gmail.com](mailto:nathanmvdh@gmail.com) if you don't want to post it publicly here - it will contain all your zone names and system name and stuff).

Sent you the log and dump file.

**Comment by nathanvdh** [comment] 2022-10-14 10:43
Just an update:
I've assumed I am looking for a single 'bit' (1 or 0) in the airtouch 2 response message that indicates if the aircon supports the quiet fan speed or not (I could be wrong). Looking at the difference between my dumps and the ones I've received so far there are 3 possible bits (that are 1 for me and 0 for all of you) - 2 of them are in the 2 bytes immediately after the constant header, I don't know what these bytes are but it seems unlikely to me this fan speed information would be stored so soon in the message (I could be wrong). This leaves 1 remaining bit - the 5th bit after 0x124 so for now I'm just going to implement checking that. It will fix the issue for all of you and if I'm wrong then someone in the future will find out :) and hopefully let me know.

**Comment by NoirElec** [comment] 2022-10-25 12:47
Also do not have quiet setting 
[PCAP](https://drive.google.com/file/d/1yJuXBaSLC92x5RpypkqEevsJobETozS4/view?usp=sharing)

**Comment by nathanvdh** [comment] 2022-11-17 11:59
I've been very busy with uni but done now. NoirElec's dump disagrees with the rest of them and the 2 bytes after the header actually seem to change (my most recent dump from my own unit doesn't match the last one much at all), so I've got no idea now. I might just add a config entry that makes you specify if the unit supports Quiet mode or not.

**Comment by nathanvdh** [comment] 2022-11-18 05:26
Okay I've been looking in the wrong places and can't believe it's taken me this long, but I'm pretty sure I've found it now. The only issue is that your dump, @ruaandeysel, seems to indicate your AC has 4 fan speeds (like mine) whereas everyone else's only has 3 (low, med, high). Are you sure you don't have a 4th fan speed? Likely either Quiet/diffuse like mine is or perhaps a turbo mode?

**Comment by ruaan-deysel** [comment] 2022-11-18 05:35
> Okay I've been looking in the wrong places and can't believe it's taken me this long, but I'm pretty sure I've found it now. The only issue is that your dump, @ruaandeysel, seems to indicate your AC has 4 fan speeds (like mine) whereas everyone else's only has 3 (low, med, high). Are you sure you don't have a 4th fan speed? Likely either Quiet/diffuse like mine is or perhaps a turbo mode?

Here's screenshot

![image](https://user-images.githubusercontent.com/57021511/202628387-ea7d491b-a1e0-46e1-8459-9b5e4929ae8f.jpeg)

**Comment by ruaan-deysel** [comment] 2022-11-18 05:37
> Okay I've been looking in the wrong places and can't believe it's taken me this long, but I'm pretty sure I've found it now. The only issue is that your dump, @ruaandeysel, seems to indicate your AC has 4 fan speeds (like mine) whereas everyone else's only has 3 (low, med, high). Are you sure you don't have a 4th fan speed? Likely either Quiet/diffuse like mine is or perhaps a turbo mode?

Screenshot of the AirTouch app.

![image](https://user-images.githubusercontent.com/57021511/202628649-51374462-6475-4d8c-9477-a86102c86aa0.jpeg)

**Comment by nathanvdh** [comment] 2022-11-18 05:51
Okay thanks, so you have an extra 'powerful' mode. Can you tell me exactly how my current integration sets the fan speeds for you? Go through and use home assistant to set it to auto, diffuse, low, medium, high and tell me what each one actually sets on your AC. Thanks.

**Comment by nathanvdh** [comment] 2022-11-18 05:55
@ruaandeysel ^

**Comment by ruaan-deysel** [comment] 2022-11-18 06:19
> Okay thanks, so you have an extra 'powerful' mode. Can you tell me exactly how my current integration sets the fan speeds for you? Go through and use home assistant to set it to auto, diffuse, low, medium, high and tell me what each one actually sets on your AC. Thanks.

Here you go:

HA        AC
Auto    = Auto
Diffuse = Low
Low     = Medium
Medium  = High
High    = Power

**Comment by nathanvdh** [comment] 2022-11-19 12:11
> Also do not have quiet setting [PCAP](https://drive.google.com/file/d/1yJuXBaSLC92x5RpypkqEevsJobETozS4/view?usp=sharing)

Hi Noir, would you be able to give me some more info? What brand is your unit and what fan speeds does it support?

**Comment by nathanvdh** [comment] 2022-11-23 02:20
@gogreenpower @ruaandeysel @TETZUO @NoirElec @DmitryNefedov

Can you all please [enable betas for the repo](https://hacs.xyz/docs/faq/beta/) and download the new 0.3.beta1 version of the integration. Can you test if your fan speeds are correct now and let me know if you experience any warnings/errors in the logs or other issues.

<img src="https://user-images.githubusercontent.com/55475809/203457486-e3514384-7c7b-4f6b-96cc-d02e0d5e8b82.png" width=75% height=75%>

<img src="https://user-images.githubusercontent.com/55475809/203457512-8282aa61-a1e5-4ad3-b86f-e7683373b56b.png" width=75% height=75%>

**Comment by ruaan-deysel** [comment] 2022-11-23 03:17
> @gogreenpower @ruaandeysel @TETZUO @NoirElec @DmitryNefedov
> 
> Can you all please [enable betas for the repo](https://hacs.xyz/docs/faq/beta/) and download the new 0.3.beta1 version of the integration. Can you test if your fan speeds are correct now and let me know if you experience any warnings/errors in the logs or other issues.
> 
> <img alt="" width="75%" height="75%" src="https://user-images.githubusercontent.com/55475809/203457486-e3514384-7c7b-4f6b-96cc-d02e0d5e8b82.png">
> 
> <img alt="" width="75%" height="75%" src="https://user-images.githubusercontent.com/55475809/203457512-8282aa61-a1e5-4ad3-b86f-e7683373b56b.png">

@nathanvdh Thank you for releasing this beta version. I installed it and all the fan speeds are working fine now for me.

**Comment by TETZUO** [comment] 2022-11-23 04:07
> > @gogreenpower @ruaandeysel @TETZUO @NoirElec @DmitryNefedov @nathanvdh 
> > Can you all please [enable betas for the repo](https://hacs.xyz/docs/faq/beta/) and download the new 0.3.beta1 version of the integration. Can you test if your fan speeds are correct now and let me know if you experience any warnings/errors in the logs or other issues.
> > <img alt="" width="75%" height="75%" src="https://user-images.githubusercontent.com/55475809/203457486-e3514384-7c7b-4f6b-96cc-d02e0d5e8b82.png">
> > <img alt="" width="75%" height="75%" src="https://user-images.githubusercontent.com/55475809/203457512-8282aa61-a1e5-4ad3-b86f-e7683373b56b.png">
> 
> @nathanvdh Thank you for releasing this beta version. I installed it and all the fan speeds are working fine now for me.

Tested and the only issue I found is with my unit I only have low, med and high.

If I am in a mode like low then select auto, any option I select after that will always revert to the option I selected before auto mode which is this case was low.

Out side of that the mappings are working correctly

**Comment by gogreenpower** [comment] 2022-11-23 04:37
> @gogreenpower @ruaandeysel @TETZUO @NoirElec @DmitryNefedov
> 
> Can you all please [enable betas for the repo](https://hacs.xyz/docs/faq/beta/) and download the new 0.3.beta1 version of the integration. Can you test if your fan speeds are correct now and let me know if you experience any warnings/errors in the logs or other issues.
> 
> <img alt="" width="75%" height="75%" src="https://user-images.githubusercontent.com/55475809/203457486-e3514384-7c7b-4f6b-96cc-d02e0d5e8b82.png">
> 
> <img alt="" width="75%" height="75%" src="https://user-images.githubusercontent.com/55475809/203457512-8282aa61-a1e5-4ad3-b86f-e7683373b56b.png">

Working for me too, great job.

**Comment by nathanvdh** [comment] 2022-11-23 05:15
> 
> Tested and the only issue I found is with my unit I only have low, med and high.
> 
> If I am in a mode like low then select auto, any option I select after that will always revert to the option I selected before auto mode which is this case was low.
> 
> Out side of that the mappings are working correctly

Are you saying you don't have an auto fan speed at all on your airtouch?

When you say it 'will always revert' do you mean just on the home assistant display or truly on your airtouch - e.g. you are watching it on the touch panel or in the app.

Can you please cycle through modes and describe what happens both in home assistant, and also what actually happens to your airtouch. Also are there any errors or warnings in the log, thanks.

**Comment by TETZUO** [comment] 2022-11-23 09:42
> > Tested and the only issue I found is with my unit I only have low, med and high.
> > If I am in a mode like low then select auto, any option I select after that will always revert to the option I selected before auto mode which is this case was low.
> > Out side of that the mappings are working correctly
> 
> Are you saying you don't have an auto fan speed at all on your airtouch?
> 
> When you say it 'will always revert' do you mean just on the home assistant display or truly on your airtouch - e.g. you are watching it on the touch panel or in the app.
> 
> Can you please cycle through modes and describe what happens both in home assistant, and also what actually happens to your airtouch. Also are there any errors or warnings in the log, thanks.

Yes only 3 speed as per the photo. 

And yes it reverts on both HA and the panel(so the fan speed physically changes) but it only happens after I select auto.

I also have no errors reported. 

Here is a video showing everything working fine until I select auto. 

https://youtube.com/shorts/3FuxNCbT1mw?feature=share
![panel](https://user-images.githubusercontent.com/36467084/203515506-ab2abb6b-4c28-4b39-88ec-5636a3fdf804.jpg)

**Comment by TETZUO** [comment] 2022-11-23 09:42
![Uploading 4F403CA9-5179-4D55-B2F4-14A484593F05.jpeg…]()

**Comment by nathanvdh** [comment] 2022-11-23 10:19
Thanks. I thought there was always an auto mode, I guess not. Seems like I'm not done with this just yet...

**Comment by nathanvdh** [comment] 2022-11-23 10:28
> 
> Yes only 3 speed as per the photo.
> 
> And yes it reverts on both HA and the panel(so the fan speed physically changes) but it only happens after I select auto.
> 
> I also have no errors reported.
> 
> Here is a video showing everything working fine until I select auto.
> 
> https://youtube.com/shorts/3FuxNCbT1mw?feature=share ![panel](https://user-images.githubusercontent.com/36467084/203515506-ab2abb6b-4c28-4b39-88ec-5636a3fdf804.jpg)

When you do medium->auto->low->(automatic back to) medium
Do both those final ones actually change on your aircon? Do you see on the panel/app that it quickly goes from low to medium? Or does it just get stuck on medium (in this scenario) once you've tried to set auto?

**Comment by TETZUO** [comment] 2022-11-23 10:49
> > Yes only 3 speed as per the photo.
> > And yes it reverts on both HA and the panel(so the fan speed physically changes) but it only happens after I select auto.
> > I also have no errors reported.
> > Here is a video showing everything working fine until I select auto.
> > https://youtube.com/shorts/3FuxNCbT1mw?feature=share ![panel](https://user-images.githubusercontent.com/36467084/203515506-ab2abb6b-4c28-4b39-88ec-5636a3fdf804.jpg)
> 
> When you do medium->auto->low->(automatic back to) medium Do both those final ones actually change on your aircon? Do you see on the panel/app that it quickly goes from low to medium? Or does it just get stuck on medium (in this scenario) once you've tried to set auto?

Yes they actually do change on the aircon. 

The panel and app all change

**Comment by nathanvdh** [comment] 2022-11-23 11:07
Okay thanks for that. I really have no idea why that would happen, does changing it from the panel/app after you've tried setting auto in home assistant yield the same behaviour?

It doesn't really matter, though. All I'm going to do now is identify if units actually support auto mode or not, so the fix will be just to not give you the auto button.

**Comment by nathanvdh** [comment] 2022-11-24 12:38
Ok sorry to ping you all again but:
@gogreenpower @ruaandeysel @TETZUO @NoirElec @DmitryNefedov

I've put out a beta2 update that (at least tries to) detect support of an auto fan speed mode, can you all test again to make sure I haven't broken anything (and Pete/tetzuo make sure you no longer have the auto option).

It's been very painful because this information is not conveyed in the airtouch2 communications - auto and fan speed support is literally hard coded in the airtouch app based on the ac brand, gateway and number of speeds. I'm trying to reverse engineer all the rules by decompiling the app and reading through the Smali bytecode but it's not fun. Hopefully this fixes everything for you guys and if someone else discovers problems, I'll cross that bridge when I come to it.

**Comment by ruaan-deysel** [comment] 2022-11-24 19:53
> Ok sorry to ping you all again but:
> 
> @gogreenpower @ruaandeysel @TETZUO @NoirElec @DmitryNefedov
> 
> 
> 
> I've put out a beta2 update that (at least tries to) detect support of an auto fan speed mode, can you all test again to make sure I haven't broken anything (and Pete/tetzuo make sure you no longer have the auto option).
> 
> 
> 
> It's been very painful because this information is not conveyed in the airtouch2 communications - auto and fan speed support is literally hard coded in the airtouch app based on the ac brand, gateway and number of speeds. I'm trying to reverse engineer all the rules by decompiling the app and reading through the Smali bytecode but it's not fun. Hopefully this fixes everything for you guys and if someone else discovers problems, I'll cross that bridge when I come to it.

Updated and still working fine 🙂

**Comment by TETZUO** [comment] 2022-11-24 20:25
Hey mate the fan speeds are correct but if I change the speeds the speed automatically goes back to the first speed HA saw after the update. 

Also the unit operation keeps turning off the AC in HA which is replicated to the panel. 

Video for reference 

https://youtube.com/shorts/3FuxNCbT1mw?feature=share

**Comment by nathanvdh** [comment] 2022-11-24 22:25
> Hey mate the fan speeds are correct but if I change the speeds the speed automatically goes back to the first speed HA saw after the update.
> 
> Also the unit operation keeps turning off the AC in HA which is replicated to the panel.
> 
> Video for reference
> 
> https://youtube.com/shorts/3FuxNCbT1mw?feature=share

Did you update to beta2? Is the auto fan speed still visible for you in HA?

What do you mean by the second part? HA is turning off the AC when it shouldn't be?

**Comment by TETZUO** [comment] 2022-11-24 22:45
Yes it’s updated. 

The auto fan speed is no longer present. 

The issue I see is similar to before which the fan speeds changing after selecting auto. But now it happens when changing the mode of the AC and still happens to the fan speed but if any speed selected.

**Comment by nathanvdh** [comment] 2022-11-25 01:09
> Yes it’s updated.
> 
> The auto fan speed is no longer present.
> 
> The issue I see is similar to before which the fan speeds changing after selecting auto. But now it happens when changing the mode of the AC and still happens to the fan speed but if any speed selected.

Peculiar. Does your AC not support all the operation modes? (Heat, Cool, Fan, Dry, Auto?). Would you be able to do the following so I can try and work out what is different about your unit:

`pip install airtouch2==0.3b2`

Then redownload the test.py file from the same place as before, run it, and (on your actual touchpad/airtouch app) cycle through all the fan speeds and operation modes? Then compress and zip all the .dump files and .log file and email it to me? Hopefully that'll be enough info for me to work out what's going on.

**Comment by TETZUO** [comment] 2022-11-25 01:25
tried to run it but I am getting this error

C:\Users\Peter\Downloads\AC>python test.py
Traceback (most recent call last):
  File "C:\Users\Peter\Downloads\AC\test.py", line 2, in <module>
    from airtouch2 import ACFanSpeed, ACMode
ImportError: cannot import name 'ACFanSpeed' from 'airtouch2' (C:\Users\Peter\AppData\Local\Programs\Python\Python311\Lib\site-packages\airtouch2\__init__.py)

**Comment by nathanvdh** [comment] 2022-11-25 02:33
> tried to run it but I am getting this error
> 
> C:\Users\Peter\Downloads\AC>python test.py Traceback (most recent call last): File "C:\Users\Peter\Downloads\AC\test.py", line 2, in from airtouch2 import ACFanSpeed, ACMode ImportError: cannot import name 'ACFanSpeed' from 'airtouch2' (C:\Users\Peter\AppData\Local\Programs\Python\Python311\Lib\site-packages\airtouch2__init__.py)

Sorry, you should use the test.py from here:
https://github.com/nathanvdh/airtouch2-python/blob/detect-fan-speeds/tests/test.py

I forgot I was pushing to a new branch called 'detect-fan-speeds'.

**Comment by nathanvdh** [comment] 2022-11-25 10:26
I've discovered a small oversight...try beta3 now @TETZUO ?

**Comment by TETZUO** [comment] 2022-11-25 12:10
@nathanvdh Just tired and it’s working perfectly!
Fan speeds and hvac modes are no longer reverting automatically to previous settings like before.

**Comment by nathanvdh** [comment] 2022-11-25 12:30
Good to hear I will likely make this stable sometime in the next few days and close this issue

**Comment by nathanvdh** [comment] 2022-11-28 11:55
Okay I've put out a 0.3 stable release, let me know if there's any problems.

**Closed as completed by nathanvdh** 2022-11-28 11:55 UTC

**Comment by gogreenpower** [comment] 2022-11-29 00:13
Magnificent work @nathanvdh, let me know if you need any help with the zones
